const data = [
  {
    id: 1,
    name: 'Hikayen',
    postName: 'ozge.cey',
    image: require('../images/profil.jpg'),
    postImage: require('../images/portakal.jpg'),
    like: 25,
    comment: 'Xem tất cả 19 bình luận',
    explanation: 'Màu xanh lấp ánh cam',
    time: '1 ngày trước',
    timeStory: '1s',
    islike: false,
  },
  {
    id: 2,
    name: 'macellan',
    postName: 'macellan',
    image: require('../images/macellan.jpg'),
    postImage: require('../images/fintech.jpeg'),
    like: 360,
    comment: 'Xem tất cả 20 bình luận',
    explanation: 'Thank you sir @fintech',
    time: '2 ngày trước',
    timeStory: '53d',
    islike: false,
  },
  {
    id: 3,
    name: 'ezgiceylan',
    postName: 'ezgiceylan',
    image: require('../images/ezgiceylan.jpeg'),
    postImage: require('../images/oje.jpg'),
    like: 120,
    comment: '4 Xem tất cả 19 bình luận',
    explanation: 'Beautifull:)',
    time: '3 ngày trước',
    timeStory: '2s',
    islike: false,
  },
  {
    id: 4,
    name: 'catvideos',
    postName: 'catvideos',
    image: require('../images/cat.jpg'),
    postImage: require('../images/catPost.jpg'),
    like: 160,
    comment: 'Xem tất cả 10 bình luận',
    explanation: 'My big cat @cat',
    time: '5 ngày trước',
    timeStory: '3s',
    islike: false,
  },
  {
    id: 5,
    name: 'alternatif',
    postName: 'alternatifSuperApp',
    image: require('../images/alternatif.png'),
    postImage: require('../images/Afiş.png'),
    like: 220,
    comment: '110 Xem tất cả 19 bình luận',
    explanation: 'Wellcome everyone!!!',
    time: '8 ngày trước',
    timeStory: '6s',
    islike: false,
  },
  {
    id: 6,
    name: 'bfy',
    postName: 'bfy',
    image: require('../images/bfy.png'),
    postImage: require('../images/bfyPost.jpg'),
    like: 150,
    comment: 'Xem tất cả 30 bình luận',
    explanation: 'Oto connect Technology',
    time: '24 ngày trước',
    timeStory: '24s',
    islike: false,
  },
];
export default data;
